name: mace_env
channels:
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - bzip2=1.0.8
  - ca-certificates=2025.9.9
  - expat=2.7.1
  - ld_impl_linux-64=2.44
  - libffi=3.4.4
  - libgcc-ng=11.2.0
  - libgomp=11.2.0
  - libnsl=2.0.0
  - libstdcxx-ng=11.2.0
  - libuuid=1.41.5
  - libxcb=1.17.0
  - libzlib=1.3.1
  - ncurses=6.5
  - openssl=3.0.18
  - pip=25.2
  - pthread-stubs=0.3
  - python=3.10.19
  - readline=8.3
  - setuptools=80.9.0
  - sqlite=3.50.2
  - tk=8.6.15
  - wheel=0.45.1
  - xorg-libx11=1.8.12
  - xorg-libxau=1.0.12
  - xorg-libxdmcp=1.1.5
  - xorg-xorgproto=2024.1
  - xz=5.6.4
  - zlib=1.3.1
  - pip:
      - aiohappyeyeballs==2.6.1
      - aiohttp==3.13.2
      - aiosignal==1.4.0
      - ase==3.26.0
      - astroid==4.0.1
      - async-timeout==5.0.1
      - attrs==25.4.0
      - black==25.9.0
      - certifi==2025.10.5
      - cfgv==3.4.0
      - charset-normalizer==3.4.4
      - click==8.3.0
      - configargparse==1.7.1
      - contourpy==1.3.2
      - cuequivariance==0.7.0
      - cuequivariance-ops-cu12==0.7.0
      - cuequivariance-ops-torch-cu12==0.7.0
      - cuequivariance-torch==0.7.0
      - cycler==0.12.1
      - dill==0.4.0
      - distlib==0.4.0
      - e3nn==0.4.4
      - exceptiongroup==1.3.0
      - filelock==3.20.0
      - fonttools==4.60.1
      - frozenlist==1.8.0
      - fsspec==2025.9.0
      - gitdb==4.0.12
      - gitpython==3.1.45
      - h5py==3.15.1
      - identify==2.6.15
      - idna==3.11
      - iniconfig==2.3.0
      - isort==7.0.0
      - jinja2==3.1.6
      - kiwisolver==1.4.9
      - lightning-utilities==0.15.2
      - lmdb==1.7.5
      - mace-torch==0.3.14
      - markupsafe==3.0.3
      - matplotlib==3.10.7
      - matscipy==1.1.1
      - mccabe==0.7.0
      - mpmath==1.3.0
      - multidict==6.7.0
      - mypy==1.18.2
      - mypy-extensions==1.1.0
      - networkx==3.4.2
      - nodeenv==1.9.1
      - numpy==1.26.4
      - nvidia-cublas-cu12==12.8.4.1
      - nvidia-cuda-cupti-cu12==12.8.90
      - nvidia-cuda-nvrtc-cu12==12.8.93
      - nvidia-cuda-runtime-cu12==12.8.90
      - nvidia-cudnn-cu12==9.10.2.21
      - nvidia-cufft-cu12==11.3.3.83
      - nvidia-cufile-cu12==1.13.1.3
      - nvidia-curand-cu12==10.3.9.90
      - nvidia-cusolver-cu12==11.7.3.90
      - nvidia-cusparse-cu12==12.5.8.93
      - nvidia-cusparselt-cu12==0.7.1
      - nvidia-ml-py==13.580.82
      - nvidia-nccl-cu12==2.27.5
      - nvidia-nvjitlink-cu12==12.8.93
      - nvidia-nvshmem-cu12==3.3.20
      - nvidia-nvtx-cu12==12.8.90
      - opt-einsum==3.4.0
      - opt-einsum-fx==0.1.4
      - orjson==3.11.3
      - packaging==25.0
      - pandas==2.3.3
      - pathspec==0.12.1
      - pillow==12.0.0
      - platformdirs==4.5.0
      - pluggy==1.6.0
      - pre-commit==4.3.0
      - prettytable==3.16.0
      - propcache==0.4.1
      - psutil==7.1.3
      - py-cpuinfo==9.0.0
      - pygments==2.19.2
      - pylint==4.0.2
      - pyparsing==3.2.5
      - pytest==8.4.2
      - pytest-benchmark==5.1.0
      - python-dateutil==2.9.0.post0
      - python-hostlist==2.3.0
      - pytokens==0.2.0
      - pytz==2025.2
      - pyyaml==6.0.3
      - requests==2.32.5
      - scipy==1.15.3
      - six==1.17.0
      - smmap==5.0.2
      - sympy==1.14.0
      - tomli==2.3.0
      - tomlkit==0.13.3
      - torch==2.9.0
      - torch-cluster==1.6.3
      - torch-ema==0.3
      - torch-geometric==2.7.0
      - torch-scatter==2.1.2
      - torch-sparse==0.6.18
      - torch-spline-conv==1.2.2
      - torchmetrics==1.8.2
      - tqdm==4.67.1
      - triton==3.5.0
      - typing-extensions==4.15.0
      - tzdata==2025.2
      - urllib3==2.5.0
      - virtualenv==20.35.3
      - wcwidth==0.2.14
      - xxhash==3.6.0
      - yarl==1.22.0
prefix: /home/kjt/miniconda3/envs/mace_env
