name: mace_env
channels:
  - pytorch
  - nvidia
  - defaults
dependencies:
  - python=3.10.19
  - pip=25.2
  - setuptools=80.9.0
  - wheel=0.45.1
  - numpy=1.26.4
  - scipy=1.15.3
  - pandas=2.3.3
  - matplotlib=3.10.7
  - pytorch=2.4.1
  - pytorch-cuda=12.1
  - cudnn=9.1.0.70
  - readline=8.3
  - tk=8.6.15
  - xz=5.6.4
  - zlib=1.3.1
  - openssl=3.0.18
  - pip:
      - aiohttp==3.13.2
      - ase==3.26.0
      - black==25.9.0
      - configargparse==1.7.1
      - cuequivariance==0.7.0
      - cuequivariance-ops-cu12==0.7.0
      - cuequivariance-ops-torch-cu12==0.7.0
      - cuequivariance-torch==0.7.0
      - e3nn==0.4.4
      - h5py==3.15.1
      - lmdb==1.7.5
      - mace-torch==0.3.14
      - prettytable==3.16.0
      - torch-ema==0.3
      - torch-geometric==2.7.0
      - torch-scatter==2.1.2
      - torch-sparse==0.6.18
      - torch-cluster==1.6.3
      - torch-spline-conv==1.2.2
      - torchmetrics==1.8.2
      - tqdm==4.67.1
      - xxhash==3.6.0
